### ISSUE TITLE
Cant get this to load.

### ISSUE THREAD

**Issue by AllyPallies** [callmeEthan/GameHUB2#1]
When I hit the controller icon and get to the game menu I right click anything and say Layout manager doesn't work at all. returns me back but no GUI loads like in V1 did. I don't know what im doing wrong or what can be done.

**Comment by callmeEthan** [comment]
Open rainmeter, see if skin in the configuration folder actually load.
If it does, check for skin settings, like transparent, position (outside of screen) et cetera

**Comment by AllyPallies** [comment]
Yes I had noticed that, it was forced in the negative frame of my screen and fixed it. What are the default settings for Icon, cover and background for making one of your own.

**Comment by callmeEthan** [comment]
Icon are preferably 256 or 512px, background should be at your screen resolution.
For cover you can go however you like, depend on which layout you choose and screen resolution, just nothing too excessive (image larger than display resolution ect).
