### ISSUE TITLE
[Question] Bug or new feature

### ISSUE THREAD

**Issue by Ng76i4** [callmeEthan/GameHUB2#16]
New GameHUB does not remember my last layout like the previous one. Yes, it does remember my previous played game, but it always goes to the Game layout no matter which layout I opened last

**Comment by callmeEthan** [comment]
What do you use to open gamehub?

**Comment by Ng76i4** [comment]
I figured out what had happened. I opened it with "another dock". Which Execute [!WriteKeyValue "Variables" "filelayout" "page_game.inc". 
Your question answer my question
