### ISSUE TITLE
Backgrounds are misplaced on UW monitor

### ISSUE THREAD

**Issue by Magnus88** [callmeEthan/GameHUB2#17]
Hey, on my UW monitor (3440×1440) the background images arent getting scaled, thus ending up misplaced,
I dont know if this counts as a bug as its more of a feature request but i just wanted to leave this here.
Thanks!

**Comment by callmeEthan** [comment]
What's your image resolution? If your image sizs is only half your screen
resolution. Add ImageScale = 0.5 under layout [Display] section.

**Comment by Magnus88** [comment]
I was talking about the example images that come with it. Thanks for the scaling tip. I'll try that :)
