### ISSUE TITLE
change size of close button

### ISSUE THREAD

**Issue by MatiasEsf** [callmeEthan/GameHUB2#21]
Hi.!

How can I change the size of the close button...it's huge! and it looks very ugly. What file should I edit?
![Screenshot_1](https://github.com/callmeEthan/GameHUB2/assets/49958478/1522d239-0cce-4b48-9934-d2f72e4081e6)

**Comment by callmeEthan** [comment]
Close button is hard coded into background. You can edit Display.ini files in "GameHUB 2\Background"

**Comment by MatiasEsf** [comment]
> Close button is hard coded into background. You can edit Display.ini files in "GameHUB 2\Background"

thanks, solved <3

![Screenshot_1](https://github.com/callmeEthan/GameHUB2/assets/49958478/34c29ccf-e891-461e-94bf-5252df138d95)
