### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by TequilaSunsetIRL** [callmeEthan/GameHUB2#29]
Hey, I finally just switched from Gamehub1 to Gamehub2. I'm wanting to disable or at least adjust the transparency of the background element called "gradient.png" to be kind of more transparent like it was in gamehub1. Can you point me at the string in the config txt's where i can mess with that? Thanks for making such cool stuff all this time, BTW

**Comment by callmeEthan** [comment]
Check the folder "GameHUB 2\@Resources\Layout", there's "acrylic.inc" and "blur.inc", depends on which you are using. The gradient.png element should be under [Background] section.
Acrylic.inc has stronger blur than blur.inc, you can change by right-clicking on the skin > Choose layout file > Edit Layout value under [Background] section.

**Comment by TequilaSunsetIRL** [comment]
cool! thank you so much for taking time to show me. i hope you have an excellent day
