### ISSUE TITLE
layout manager is always blank

### ISSUE THREAD

**Issue by greenfuzzystuff** [callmeEthan/GameHUB2#3]
started trying to use it but after i chose a preset the layout manager comes up blank. whenever i pick a different preset, layout manager is blank and preset doesnt change.  the buttons on the left (game, app, emulator) dont appear abut my cursor shows somethings clickable.

**Comment by callmeEthan** [comment]
That's alot, can you show screenshot

**Comment by Bluenitro0110** [comment]
I also ended up having this issue, for me, the fix was that the layout manager was positioned off-screen and needed repositioning from the rainmeter manage section
