### ISSUE TITLE
Rainmeter crash when running app with UAC confirmation

### ISSUE THREAD

**Issue by azolkos** [callmeEthan/GameHUB2#4]
The UAC confirmation dialog that appears when certain executables are launched from via GameHub2 results in Rainmeter crash. After clicking on the app gamehub does not minimize, then the UAC confirmation dialog appears in the background. I close gamehub with the top right "X", then click the UAC dialog. Then the app launches (or doesn't if not no admin rights provided) and Rainmeter crashes.
Turning UAC to "never notify" fixed the issue. I suspect it has something to do with the "loading icon", that appears when apps are launched, since it doesn't appear at all in the case when UAC confirmation is needed. I will try to find and disable this "loading icon" (don't know yet how) and update when I know more.

**Comment by callmeEthan** [comment]
You can disable loading icon effect in the layout file, in the LaunchAction value.
The UAC dialog would appear on top of rainmeter, confirming it would close gamehub as usual for me, so I'm not sure what wrong here.
You can also bypass the UAC by running rainmeter as administrator.

**Comment by azolkos** [comment]
Disabling the loading icon did not solve the problem. Running Rainmeter as admin is a workaround (just one UAC dialog appears on rainmeter startup). However I my case the behavior is different than you described. If I run Rainmeter normally and launch an app that requires UAC confirmation, the dialog appears on top of rainmeter for a split second, then goes to background. To click it i have to close the fullscreen with "X" and then confirm the dialog. After confirmation the app runs and Rainmeter crashes. Maybe something is not right with the exit script or window focus? I am not sure how one can reproduce this issue.

**Comment by callmeEthan** [comment]
likely your windows version's not 10?

**Comment by azolkos** [comment]
I am running Windows 10 Pro, Rainmeter 4.3.1.3321, and newest GameHub2.

**Comment by callmeEthan** [comment]
can you show screenshot of UAC dialog

**Comment by azolkos** [comment]
![image](https://user-images.githubusercontent.com/29781344/74043058-f91dfb80-49c8-11ea-815f-070dc9d13276.png)

The dialog box is behind Rainmeter. I found out I can drag it by clicking "in between" the panels. If I drag the box to where I can click the confirmation then everything runs properly. However if I first close the fullscreen view and then confirm, then the crash happens.

**Comment by callmeEthan** [comment]
Try look in Control Panel, under Security and Maintenance, Change User Control Setting, "do not dim my desktop" most likely the cause, just set it back to default.

**Comment by azolkos** [comment]
This fixed the issue :) However it's too bad it doesn't work with "do not dim my desktop" option. The fullscreen UAC dialog is annoying.
