### ISSUE TITLE
List App cut the cover

### ISSUE THREAD

**Issue by AlePini** [callmeEthan/GameHUB2#7]
![image](https://user-images.githubusercontent.com/1899741/104068316-fc3af080-5204-11eb-8cd0-23033ce0a674.png)
As you can see the cover is getting cropped.
Using a 1440p monitor and this appen when I use 1080p wallpaper

**Comment by ravenwolf123** [comment]
Bump

**Comment by callmeEthan** [comment]
Replace or resize your background image to fit your screen resolution
