### ISSUE TITLE
Icon doesn't change

### ISSUE THREAD

**Issue by FunMLG** [callmeEthan/GameHUB2#9]
Hello, when I want to change a game icon, all icons change (I don't know how to explain but here is a screenshot)
![unknown](https://user-images.githubusercontent.com/44449087/117571183-afd9c180-b0cd-11eb-8545-cde25635f3ff.png)

And if I create an entry, the default icon is the same as those in other entries created before (screenshot)
![unknown (1)](https://user-images.githubusercontent.com/44449087/117571221-e4e61400-b0cd-11eb-84ce-51b9db87b653.png)

I've already tried to reboot my computer, it didn't work. I also tried to reboot rainmeter, but still nothing...

If you know how to solve it, I'd like to know it please 😅

**Comment by callmeEthan** [comment]
make sure icon file doesn't have conflicting name, otherwise they'll be overwrite when copy

**Comment by FunMLG** [comment]
I don't have GameHub2 anymore but thanks for the suggestion

**Comment by callmeEthan** [comment]
okay but have you tried gamehub 3

**Comment by FunMLG** [comment]
I'm only on Linux now :sweat_smile:

**Comment by callmeEthan** [comment]
oh okay I was just messing with ya
